export const backend_host = "http://localhost:8000"
// export const backend_host = "https://backend.liberty-realty.ru"
export const phone_site = "+7 952 836 62 62"
export const email_site = "LibertySochi@yandex.ru"
export const office_site = "Сочи, улица Волжская, 30"